version: '3.7'

services:

  db:
    image: postgres:14.2-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: pgres
      POSTGRES_PASSWORD: pgres
      POSTGRES_DB: stardew_valley
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
