services:

  api:
    image: golang:1.18.4-alpine3.16
    restart: always
    environment:
      API_SERVER_DB_HOST: db
      API_SERVER_DB_PORT: 5432
      API_SERVER_DB_USER: pgres
      API_SERVER_DB_PASSWORD: pgres
      API_SERVER_DB_DATABASE: stardew_valley
      API_SERVER_DB_DSN_OPTS: "TimeZone=Europe/Berlin"
    volumes:
      - "./:/app"
    working_dir: "/app"
    command: "go run -tags gingonic ./cmd/server"
    ports:
      - "4200:4200"
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: pgres
      POSTGRES_PASSWORD: pgres
      POSTGRES_DB: stardew_valley
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
