services:

  api:
    image: golang:1.23.2-alpine3.19
    restart: no
    volumes:
      - "./:/app"
    working_dir: "/app"
    command: "go run -tags gingonic ./cmd/server"
    ports:
      - "4200:4200"
